Move =~ operator in value_parser down
... because it will try to issue the =~ operator
on for example a true (TrueClass) value which
gives error:

  undefined method `=~' for true:TrueClass

Signed-off-by: Tobias Urdin <tobias.urdin@binero.com>